apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-knd824
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-knd824
  namespace: my-nginx-knd824
  labels:
    name: nginx-knd824
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-knd824
  template:
    metadata:
      namespace: my-nginx-knd824
      labels:
        name: nginx-knd824
    spec:
      containers:
      - name: nginx-knd824
        image: nginx
        ports:
        - containerPort: 80

